#################################################################
# PyMini Keymap configurations
#################################################################

key_delete:
- <Delete>
- <BackSpace>
- e
- u
key_deselect:
- <Escape>
- q
- o
key_erase:
- e
- o
key_escape:
- q
- u
key_multi_select:
- <Shift_L>
- <Shift_R>
key_pan_down:
- s
- k
key_pan_left:
- a
- j
key_pan_right:
- d
- l
key_pan_up:
- w
- i
key_reset_focus:
- <space>
key_scroll_rapid:
- <Shift_L>
- <Shift_R>
key_select_all:
- <Control-a>
key_toobar_zoom:
- z
key_toolbar_pan:
- p
key_toolbar_zoom:
- z
key_zoom_in_x:
- j
key_zoom_in_y:
- i
key_zoom_out_x:
- l
key_zoom_out_y:
- k
key_zoom_x:
- null
