#################################################################
# PyMini system configurations
#################################################################

config_autoload: '1'
config_autosave: '1'
config_file_autodir: '1'
config_undo_stack: '2'
config_user_path: C:/Users/megum/Documents/GitHub/PyMini/app/config/user_config.yaml
