#################################################################
# PyMini user configurations
#################################################################

adjust_baseline_mode: mean
adjust_baseline_signal: All sweeps
adjust_baseline_target: All sweeps
adjust_fixed: '0'
adjust_range_left: '0'
adjust_range_right: '1'
analysis_mode: mini
channel_option: ''
data_display_amplitude: '1'
data_display_baseline: '1'
data_display_channel: '1'
data_display_decay: '1'
data_display_decay_func: '1'
data_display_direction: '1'
data_display_halfwidth: '1'
data_display_rise: '1'
data_display_time: '1'
detector_auto_radius: '60'
detector_direction: positive
detector_max_decay: none
detector_max_hw: None
detector_max_points_decay: '40000'
detector_max_rise: None
detector_min_amp: '0.3'
detector_min_decay: '0'
detector_min_hw: '0'
detector_min_rise: '0'
detector_points_baseline: '100'
detector_search_radius: '5.0'
detector_update_events: '0'
filter_kernel: '11'
force_axis_limit: '0'
force_channel: '0'
force_channel_id: '0'
max_x: auto
max_y: auto
min_x: auto
min_y: auto
navigation_fps: '12'
navigation_mirror_x_scroll: '1'
navigation_mirror_y_scroll: '1'
navigation_scroll_percent: '3'
navigation_zoom_percent: '10'
show_decay: '1'
show_peak: '1'
show_start: '1'
style_event_color_decay: blue
style_event_color_end: purple
style_event_color_highlight: red
style_event_color_peak: yellow
style_event_color_start: red
style_event_pick_offset: '0'
style_trace_highlight_color: red
style_trace_line_color: black
style_trace_line_width: '0.25'
sweep_picker_offset: '20'
trace_info: ''
trace_mode: continuous
window_param_guide: '0'
