#################################################################
# PyMini Defaults
#################################################################
# This file contains the default configuration options
# for PyMini. IT SHOULD NOT BE EDITED!
#
# user-defined parameters should be named exactly as the default
# counterpart in this file, without the 'default_' tag
#
# widgets that use these parameters should also be named exactly
# as the default variable name, without hte 'default_' tag
#################################################################

#aesthetics
default_geometry :
  - 900
  - 600

default_relative_cp_width : 0.25
default_cp_width : 250
default_font_size : 9
default_separator : true
default_label_length: 25
default_entry_width : 10
default_progress_bar_color : 'blue'
default_gp_height : 450
default_pw_handlesize : 15

# navigation
default_scroll_percent : 10
default_nav_wait : 100
default_nav_fps : 10
default_zoom_percent : 10


#detector parameters
default_direction : 'positive'
default_min_amp : 0.3
default_points_baseline : 100
default_points_search : 300
default_min_decay : 0
default_max_points_baseline : 1000
default_max_points_decay : 40000
default_manual_pixel_offset : 0
default_update_events : 0
default_save_detector_preferences : 0
default_min_auc : 0

#style
default_min_x : 'auto'
default_max_x : 'auto'
default_min_y : 'auto'
default_max_y : 'auto'
default_apply_axis_limit : 0
default_line_color : 'black'
default_line_width : 0.25
default_major_tick : 'auto'
default_minor_tick : 'auto'
default_event_color : 'yellow'
default_baseline_color : 'red'
default_decay_color : 'blue'
default_highlight_color: 'red'
default_save_style_preferences : 0

#system
system_default_config_path :
  - 'DIR'
  - 'config'
  - "user_config.yaml"
system_default_system_path :
  - 'DIR'
  - 'config'
  - 'pymini_config.yaml'
system_default_config_autoload : 0
system_default_config_autosave : 0