#################################################################
# PyMini Defaults
#################################################################
# This file contains the default configuration options
# for PyMini. IT SHOULD NOT BE EDITED!
#
# user-defined parameters should be named exactly as the default
# counterpart in this file, without the 'default_' tag
#
# widgets that use these parameters should also be named exactly
# as the default variable name, without hte 'default_' tag
#################################################################

# version
version : 'b0.1.0'

#aesthetics
default_geometry :
  - 900
  - 600

default_relative_cp_width : 0.25
default_cp_width : 250
default_font_size : 9
default_separator : true
default_label_length: 25
default_entry_width : 10
default_progress_bar_color : 'blue'
default_gp_height : 450
default_pw_handlesize : 15

# navigation
default_min_x : 'auto'
default_max_x : 'auto'
default_min_y : 'auto'
default_max_y : 'auto'
default_apply_axis_limit : 0
default_scroll_percent : 3
default_nav_fps : 12
default_zoom_percent : 10
default_mirror_y_scroll : 1
default_mirror_x_scroll : 1


#detector parameters
default_detector_direction : 'positive'
default_detector_min_amp : 0.3
default_detector_points_baseline : 100
default_detector_points_search : 300
default_detector_min_decay : 0
default_detector_min_auc : 0
default_detector_min_hw : 0
default_detector_min_rise : 0
default_detector_max_points_baseline : 1000
default_detector_max_points_decay : 40000
default_detector_manual_pixel_offset : 0
default_detector_update_events : 0
default_detector_save_detector_preferences : 0

default_data_export_all : 1
default_data_display_time : 1
default_data_display_amplitude : 1
default_data_display_amplitude_unit : 1
default_data_display_decay : 1
default_data_display_decay_unit : 1
default_data_display_decay_time : 1
default_data_display_rise : 1
default_data_display_rise_unit : 1
default_data_display_halfwidth : 1
default_data_display_halfwidth_unit : 1
default_data_display_baseline : 1
default_data_display_baseline_unit : 1
default_data_display_auc : 0
default_data_display_start : 1
default_data_display_end : 1
default_data_display_channel : 1

#style
default_style_trace_line_color : 'black'
default_style_trace_line_width : 0.25
default_major_tick : 'auto'
default_minor_tick : 'auto'
default_style_event_color_peak : 'yellow'
default_style_event_color_start : 'red'
default_style_event_color_end : 'purple'
default_style_event_color_decay : 'blue'
default_style_event_color_highlight: 'red'
default_style_trace_highlight_color : 'red'

default_show_peak : "1"
default_show_decay_constant : "1"
default_show_start : "1"
default_show_end : ""

#system
default_config_user_path :
  - 'DIR'
  - 'config'
  - "user_config.yaml"
default_config_system_path :
  - 'DIR'
  - 'config'
  - 'pymini_config.yaml'
default_config_autoload : 1
default_config_autosave : 1
default_config_file_autodir : 1

# channel
default_channel_option : ""
default_force_channel : 0
default_force_channel_id: 0


# sweep
default_export_sweep : 1

# menu
default_trace_mode : 'continuous'