#################################################################
# PyMini Defaults
#################################################################
# This file contains the default configuration options
# for PyMini. IT SHOULD NOT BE EDITED!
#################################################################

#aesthetics
default_geometry : [900,600]
default_relative_cp_width : 0.25
default_font_size : 9
default_separator : true
default_label_width : 150
default_entry_width : 10

#detector parameters
default_direction : 'positive'
default_min_amp : 0.3
default_points_baseline : 100
default_points_search : 300
default_min_decay : 0
default_max_points_baseline : 1000
default_max_points_decay : 40000
default_manual_pixel_offset : 0
default_update_events : 0

#style
default_min_x : 'auto'
default_max_x : 'auto'
default_min_y : 'auto'
default_max_y : 'auto'
default_line_color : 'black'
default_major_tick : 'auto'
default_minor_tick : 'auto'
default_peak_color : 'yellow'
default_highlight_color: 'red'