#################################################################
# PyMini Keymap configurations
#################################################################

key_copy:
- <Control-c>
key_delete:
- <Delete>
- <BackSpace>
- e
- u
key_deselect:
- <Escape>
- q
- o
key_erase:
- e
key_escape:
- q
key_multi_select:
- <Shift_L>
- <Shift_R>
key_pan_down:
- s
key_pan_left:
- a
key_pan_right:
- d
key_pan_up:
- w
key_reset_focus:
- <space>
key_scroll_rapid:
- <Shift_L>
- <Shift_R>
key_select_all:
- <Control-a>
key_select_window:
- <Control-A>
key_toolbar_pan:
- p
key_toolbar_zoom:
- m
key_undo:
- <Control-z>
- <Control-z>
key_zoom_in_x:
- j
key_zoom_in_y:
- i
key_zoom_out_x:
- l
key_zoom_out_y:
- k
