#################################################################
# System configurations
#################################################################

config_path :
  - 'DIR'
  - 'config'
config_fname : 'user_config'

config_autoload : 1