#################################################################
# PyMini user configurations
#################################################################

direction: positive
manual_pixel_offset: '0'
max_points_baseline: '1000'
max_points_decay: '40000'
min_amp: '0.3'
min_decay: '0'
points_baseline: '100'
points_search: '300'
save_detector_preferences: '1'
update_events: '0'
apply_axis_limit: '0'
baseline_color: red
decay_color: blue
event_color: yellow
highlight_color: red
line_color: black
max_x: auto
max_y: auto
min_x: auto
min_y: auto
save_style_preferences: '1'
