#################################################################
# PyMini system configurations
#################################################################

config_autoload: '1'
config_autosave: '1'
config_path: D:\megum\Documents\GitHub\PyMini\pymini\config\user_config.yaml
file_autodir: '1'
