#################################################################
# PyMini user configurations
#################################################################

direction: positive
manual_pixel_offset: '0'
max_points_baseline: '1000'
max_points_decay: '40000'
min_amp: '0.3'
min_decay: '0'
points_baseline: '100'
points_search: '300'
save_detector_preferences: '0'
update_events: '0'
