#################################################################
# PyMini system configurations
#################################################################

system_autoload: '1'
system_autosave: '1'
system_data_dir: D:\megum\Documents\GitHub\PyMini-GHD\PyMini-GHD\simplyfire
system_undo_stack: '2'
